### ISSUE TITLE
Add BLAKE2s

### ISSUE THREAD

**Issue by cfcs** [mirage/digestif#13]
Hello, I'm working on an implementation of the [WireGuard VPN protocol](https://www.wireguard.com/) for MirageOS, and I need BLAKE2s for that.

I don't know if this would be the right place to request it / add it, but if it is trivial for you to add it, that would make everything easier for me! <3

**Comment by dinosaure** [comment]
Yeah, it's the good place 👍 . I will make an OCaml implementation and a C implementation soon.

**Comment by cfcs** [comment]
Thank you!

**Comment by avsm** [comment]
@cfcs -- Wireguard! I can't wait to see this!

**Comment by cfcs** [comment]
@avsm hold your horses; I need to *a lot* of C code running in MirageOS (Curve25519 ECDH, BLAKE2s, ChaCha20, [..]) first, so it'll take some time to get everything in order :)

**Comment by dinosaure** [comment]
About the Curve25519 implementation, I did an [OCaml implementation](https://github.com/oklm-wsh/Callipyge) (not fast). If you want a C implementation, I can put in my TODO a switching of my implementation in the same pattern than `digestif` (an OCaml impl. and a C impl.).

**Comment by cfcs** [comment]
@dinosaure Ah, very cool! For starters I don't really care about speed, or about C implementations - it will certainly be easier to get pure modules running on Mirage. I can't get the Curve25519 library to work though (neither with the example nor with my own module) - the output is always nil. Could you have a look at it?

**Comment by dylangerdaly** [comment]
@cfcs did you get very far with WireGuard Mirage? I'm willing to chip in for development, both development and financially.

**Comment by cfcs** [comment]
@dylangerdaly No, sadly I decided that WireGuard had inferior security properties compared to OpenVPN and got a bit demotivated. :(

**Comment by samoht** [comment]
btw, @emillon has started an implementation of the noise protocol see https://github.com/emillon/ocaml-noise and https://discuss.ocaml.org/t/ann-an-implementation-of-the-noise-protocol-framework/2539/4; we hope have a WireGuard implementation at one point, please get in touch if you are interested.
