### ISSUE TITLE
Build error while running `make deps` with mirage/mirage-www

### ISSUE THREAD

**Issue by davisuga** [mirage/digestif#136]
I just cloned the [mirageos website repo](https://github.com/mirage/mirage-www) and run
`make switch` (Which worked fine)
and then
`make deps`
Output:
```
#=== ERROR while compiling digestif.1.1.1 =====================================#
# context     2.1.0 | linux/x86_64 | ocaml.4.14.0 | git+https://github.com/mirage/mirage-dev.git
# path        ~/gits/mirage-www/_opam/.opam-switch/build/digestif.1.1.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build ./install/install.ml
# exit-code   2
# env-file    ~/.opam/log/digestif-238769-bd9bc9.env
# output-file ~/.opam/log/digestif-238769-bd9bc9.out
### output ###
# ./install/install.ml: 3: let: not found
# ./install/install.ml: 4: freestanding_linkopts = "-l:libdigestif_freestanding_stubs.a": not found
# ./install/install.ml: 6: let: not found
# ./install/install.ml: 7: match: not found
# ./install/install.ml: 8: Syntax error: "|" unexpected
```
OS: Linux Mint 20.02 Uma
OCaml: 4.14
Opam: 2.1.0
Dune: 3.0.3

**Comment by dinosaure** [comment]
It seems that this instruction:
https://github.com/mirage/digestif/blob/7adc43cc8d1d80c2d9104dabd5730425b1b7ace8/digestif.opam#L32

Is not executed properly with OCaml. Not sure where is the error. I will try to look deeper and fix your issue.

**Comment by dinosaure** [comment]
@RyanGibb I suspect that you currently trying to compile `mirageos` (on another system) and I would like to know if you got the same issue as @davisuga.

**Comment by RyanGibb** [comment]
Hi @dinosaure. I did not have this issue, but I was only compiling the [mirage unikernel ](https://github.com/mirage/mirage-www#mirageos-unikernel).

**Comment by dinosaure** [comment]
Hmmhmm, I think the best is just to delete such code. I trying to figure out how long I can keep it and break the support of MirageOS 3 but this code is bad in anyway I will just delete it. Thanks for your patience @davisuga and hope that I did not block anything.
