### ISSUE TITLE
Variable Blake2 digest size

### ISSUE THREAD

**Issue by vbmithr** [mirage/digestif#20]
BLAKE2b (or just BLAKE2) is optimized for 64-bit platforms—including NEON-enabled ARMs—and produces digests of any size between 1 and 64 bytes
BLAKE2s is optimized for 8- to 32-bit platforms and produces digests of any size between 1 and 32 bytes 

I need a possbility to set the digest size :)

**Comment by dinosaure** [comment]
Hmmhmm, yeah I will figure about that, I already know about this variable but I believed it's enough to no provide it.

**Comment by dinosaure** [comment]
See #21

**Comment by dinosaure** [comment]
Done by #23
