### ISSUE TITLE
streaming and referentially transparent

### ISSUE THREAD

**Issue by hannesm** [mirage/digestif#28]
looking into the API, I was wondering whether you've any plans for adapting https://github.com/mirleft/ocaml-nocrypto/commit/a9f94f8466e9f88e5f9b4d0ae1c588d7666fef5f -- imho this improves the usage in certain scenarios such as streaming (and having `feed` returning a `ctx`, rather than mutating, is a good idea imho)!?

**Comment by dinosaure** [comment]
Yah, we already talk about that with @cfcs and I put it my TODO for the next release 👍 !

**Comment by dinosaure** [comment]
See #29
