### ISSUE TITLE
[New hash] Whirlpool

### ISSUE THREAD

**Issue by myrage2000** [mirage/digestif#36]
Hi,
I am porting a personal project (it will be open source soon) from C++ to OCaml.
I think that Whirlpool is a good hash function and I would like to use it in OCaml if possible.

What do you think of a Whirlpool implementation ?

Thanks

**Comment by dinosaure** [comment]
I put it in my TODO :+1:, however, we did a big change a few days ago and I freeze features for the next release (and your hash implementation will not be implemented for 0.6 ...). However, then, I will happy to implement/integrate it in `digestif.0.7`.

**Comment by myrage2000** [comment]
Thanks a lot !

**Comment by hannesm** [comment]
see #77 :)
