### ISSUE TITLE
How to access the digest as bytes?

### ISSUE THREAD

**Issue by emillon** [mirage/digestif#45]
Hi!

I'm computing a hash and I'm trying to access the resulting digest as bytes (not hex-encoded). Is there a way to access the underlying `string`? At the moment I'm using `to_hex` and decoding it back, but this seems wasteful.

Thanks!

**Comment by dinosaure** [comment]
We choose to use a `private string` to be referentially transparent - then, a test case of `ocaml-git` highlights a bug when `type hash = bytes` (a side-effect somewhere changes values of the hash). The best for you is to destruct and cast with `Bytes.of_string` if you really want your hash as a `bytes`.

**Comment by emillon** [comment]
I'm not specifically after the `bytes` type (the title was unclear), I just wanted an unencoded value (the underlying `string`).

I didn't know that you could coerce a private type abbreviation, but `digest :> string` is exactly what I was after. Thanks!
