### ISSUE TITLE
Linking problem

### ISSUE THREAD

**Issue by dinosaure** [mirage/digestif#49]
```
$ utop -require digestif,digestif.c
# open Digestif;;
# SHA.digest_string "a";;
Error: Reference to undefined global `Digestif'
```

Close to #44

**Comment by dinosaure** [comment]
Fixed by #53.

**Comment by mseri** [comment]
This is still broken when running `dune utop` and the project links against `digestif`. Not sure if this is a more general dune issue, but it does work with other libraries like `nocrypto`

**Comment by dinosaure** [comment]
Your sure you link with `digestif.c` or `digestif.ocaml` ? Because, I just tested:

```sh
$ utop -require digestif.c
# Digestif.SHA1.digest_string "hello";;
```

 And it's work. For sure, if you do:

```sh
$ utop -require digestif
# Digestif.SHA1.digest_string "hello";;
```

This does not work because you don't have an implementation of the `Digestif` module (only the `*.cmi`). This is a weird but expected behavior.

**Comment by mseri** [comment]
Oh I see. I need to explicitly choose between the `c` or `ocaml` implementations. I thought that was automatic once I was adding `digestif` in `libraries`

**Comment by dinosaure** [comment]
As a library (like `git`), you just need to link with `digestif` if you want to play with what implementations (`digestif.c` or `digestif.ocaml`) implement - it's possible to do that only when you want to produce a `*. cma` file (which does not require implementation but only interface). Then, when you want a binary, you need to add, as a dependency, `digestif.c` or `digestif.ocaml` (choose which implementation you want).

The main problem (from `dune`) is the non-transitivity of this dependence. For example, `git-unix` (a library) links with `digestif.c` and then, some tests link with `git-unix` but we need to say again to link with `digestif.c` on these binaries even if `git-unix` has this dependency. But it will be fixed soon.
