### ISSUE TITLE
Where is the documentation ?

### ISSUE THREAD

**Issue by dinosaure** [mirage/digestif#5]
By the trick to link with the C stub or the pure OCaml implementation, `ocamlbuild` can not make a documentation.

**Comment by Ulrar** [comment]
That's a good question. Also it would be nice, for those of us who don't speak crypto, to provide an example or two as to how this is supposed to be used, because even looking at the test file I have no idea as to how hmac is supposed to be called. Thanks !

**Comment by dinosaure** [comment]
Hi, you are true and I really would like to fix it but it's much more about build-system than this project. However, I think, from previous improvements needed by `ocaml-git`, it's possible now to generate a documentation.

About `hmac`, signature is:

```ocaml
val hmac: key:buffer -> buffer -> t
```

For any hash algorithm with `Bytes.t` as input and output or `Bigstring.t` as input and output. That means, if you want to generate a keyed-hash (SHA1), you should write:

```ocaml
# let hash = Digestif.SHA1.Bytes.hmac ~key:(Bytes.of_string "my-key") (Bytes.of_string "my-message");;
- Bytes.t
```

Then, you can use `Digestif.SHA1.Bytes.to_hex` to have the hexadecimal representation of your hash. Finally, you can define a short-cut on top of your program like: `module SHA1 = Digestif.SHA1.Bytes` precisely because `Bytes.t` and `Bigstring.t` are incompatible.

**Comment by Ulrar** [comment]
I see, and I assume that to check you just re-sign the message and then use compare on both signatures ? What are init, get and feed used for, just for my own curiosity ?
Thanks !

**Comment by dinosaure** [comment]
`init`, `get` and `feed` are a couple of functions which need (or create) a `state` to be used in an imperative context. In other words, `digest : buffer -> t` (which produces a hash of your buffer) is implemented like this:

```ocaml
module SHA1 = Digestif.SHA1.Bytes

let digest content =
  let state = SHA1.init () in
  SHA1.feed state content;
  SHA1.get state
```

This implementation is useful when you want to compute a data flow (and feed `state` with each chunk of your flow). Then, you just need to use `get` to ... _get_ the final hash.

**Comment by dinosaure** [comment]
See #49

**Comment by dinosaure** [comment]
The documentation exists here: https://mirage.github.io/digestif
