### ISSUE TITLE
Incorrect OCaml implementation of SHA256?

### ISSUE THREAD

**Issue by darrenldl** [mirage/digestif#6]
When compiling with digestif.ocaml, the SHA256 hash result obtained via feeding and getting does not match the Nocrypto's one.

But when compiled with digestif.c, the hash matches.

When compiled with digestif.ocaml, it seems that the hashes mismatch as well if feeding size is different for each round.

I have not tried other hash algorithms.

Please let me know if you want me to provide full code to demonstrate the issue.

**Comment by dinosaure** [comment]
I confirm this bug. I did quickly the OCaml implementation and it was not followed by a good test suit. I take this opportunity to make a new test 👍 ! I catched your bug so, when all is ok, I will make a new release. Thanks for your report.

**Comment by darrenldl** [comment]
Awesome! Looking forward to the next release.

**Comment by dinosaure** [comment]
You can try with #8 and if all is ok, I will start the next release.

**Comment by darrenldl** [comment]
It seems to work okay.

But I was not testing on a proper test suite(just swapped the hashing part of a program).

**Comment by darrenldl** [comment]
I also noticed the OCaml implementation seems to be slower(have not done proper benchmark, but noticed my program ran a bit jittery when hashing).

I am not sure if that is fixable though.

**Comment by dinosaure** [comment]
Yes, the OCaml implementation uses the boxed `Int32` and `Int64` instead an unboxed value. This is the main issue about the performance. We will try to think a new way to optimize this part but it's not easy.

But we keep this issue in the "head TODO".
