### ISSUE TITLE
Use default implementation for library variants

### ISSUE THREAD

**Issue by samoht** [mirage/digestif#90]
See https://dune.readthedocs.io/en/stable/variants.html#default-implementation

This will fix loading in the toplevel and simplify the usage of the library quite a lot.

**Comment by dinosaure** [comment]
This is the case into digestif.0.7.3 and master (see src/dune). Despite an incompatibility with the old trick and the dune's variant, I released a special version to have a compatibility with Mirage 3.

I did the same for checkseum (0.0.9 where 1.0.0 was released before). People who wants to use dune's variant should just add a conflict with digestif.0.7.4.

**Comment by samoht** [comment]
There is something odd with the versioning:
- checkseum 0.9 doesn't have variants but checkseum 1.0 have
- digestif 0.7.4 doesn't have variants but digestif 0.7.3 have

why not keeping the digestif 0.7.* without variant and start releasing digestif 0.8. with variants? That'll be much easier to understand what happens -- this will also allow mirage3 to just add a conflict with digestif>4 instead of having to select the exact version to use.

**Comment by dinosaure** [comment]
If we introspect history:
`checkseum.1.0.0` has variants
`digestif.0.7.3` has variants

At this stage, no compatibility package was done for Mirage 3.

About `checkseum`, to avoid trouble, we decided to make a new release `checkseum.0.0.9` __after__ `checkseum.1.0.0`. However, we are not able to do the same with `digestif` where:

- `digestif.0.7` integrates too much fixes (back to `digestif.0.6` is not safe)
- `digestif.0.7.2` & `digestif.0.7.3` integrates dune's variants
- `digestif.0.7.3` fixes a _segfault_ in BLAKE2B C implementation

Solution was to do a fake release (`digestif.0.7.4`) to have a compatible version with Mirage 3. A possible solution is to make, again, a fake release `digestif.0.8` without any change with `digestif.0.7.3` but just to have an higher priority from `digestif.0.7.4` on OPAM.

**Comment by hannesm** [comment]
@dinosaure imho releasing 0.8.0 would clean up confusion!

**Comment by dinosaure** [comment]
Fix by https://github.com/ocaml/opam-repository/pull/14870

**Comment by samoht** [comment]
Many thanks!
